### ISSUE TITLE
Remove Partial<> from Entry.sys 

### ISSUE THREAD

**Issue by nicatsolent** [contensis/contensis-delivery-api#18]
Hello,

I'm using the contensis-delivery-api in our project with TypeScript, and I'm finding that on the Entry interface - the sys properties are optional, meaning that we have to typecheck sys properties which should always be there https://www.contensis.com/help-and-docs/apis/delivery-js/model/entry.

The issue is caused by contensis-delivery-api\src\models\Entry.ts where sys is being set to Partial<EntrySys> rather than EntrySys, making all sys properties optional.

Would it be possible to update this so that standard sys properties are required? If you're happy to change this, I could submit a PR with the change.

Thanks,

Nic

**Comment by alexpop-zengenti** [comment]
Just realised I missed the notification for this issue. We will have a look into this and get back to you soon.
Alex

**Comment by alexpop-zengenti** [comment]
Hi Nic,
I think your changes look good - they just need a bit more work.
I checked and the only non - nullable properties in EntrySys are versionStatus, id, uri, allUris, language, dataFormat and contentTypeId. 
Could you please make sure that every other property is marked as nullable? We will update the docs to reflect these changes.

**Comment by alexpop-zengenti** [comment]
Hi Nic, 
We will accept your pull request and make further changes based on it.

**Comment by alexpop-zengenti** [comment]
We released version 1.1.9 that has some of your changes plus a couple of additional ones.

**Comment by nicatsolent** [comment]
@alexpop-zengenti Sorry missed your original reply, thanks for accepting!
